/**
 * InsiEDR Telemetry & Domain Model Type Definitions
 * =================================================
 *
 * Architectural Role:
 *   Defines the complete strongly-typed data contracts shared between the
 *   FastAPI ASGI backend, PostgreSQL storage schemas, the ML inference bridge
 *   (RVFL + XGBoost), the rule-based Heuristics engine, and the frontend React SPA.
 *
 * Primary Data Sources:
 *   - Telemetry Ingestion: Emitted by Windows/Linux agents (File, Device, Logon, HTTP).
 *   - Risk Aggregation: Produced by `server/risk/aggregator.py` and `server/detectors/`.
 *   - Machine Learning: Inferred by `server/model_bridge.py` (v2 artifacts).
 *   - Storage Schema: Directly maps to PostgreSQL tables (`agents`, `risk_events`, `collector_results`).
 *
 * Safe Modification Guidelines:
 *   - When adding fields, ensure backward compatibility: use optional fields (`?:`).
 *   - Fields like `correlated_signals_json` can be delivered as a parsed JSON object
 *     or a raw serialized string depending on whether it originated from SSE or REST.
 */

/**
 * Categorical severity tiers assigned to endpoint risk scores.
 * - CRITICAL: Risk Score >= 85.0 (Immediate SOC escalation required)
 * - HIGH:     Risk Score >= 60.0 (Elevated anomalous pattern detected)
 * - MEDIUM:   Risk Score >= 35.0 (Moderate deviation from baseline)
 * - LOW:      Risk Score < 35.0  (Operating within normal behavioral bounds)
 */
export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/**
 * Standard CERT Insider Threat Scenario detection flag.
 * Maps to certified insider threat patterns (e.g., Data Exfiltration, Privilege Abuse).
 */
export interface CertScenario {
  id: string;
  description: string;
}

/**
 * Single heuristic rule match emitted by `heuristics/detector.py`.
 */
export interface HeuristicDetection {
  scenario: string;
  reasons: string[];
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL' | 'INFO';
  score: number;
}

/**
 * Sub-scores across the four primary telemetry monitoring vectors.
 * Keys may appear as uppercase (`FILE`, `DEVICE`, `LOGON`, `HTTP`) from Python enums
 * or lowercase (`file`, `device`, `logon`, `http`) from JSON serializations.
 */
export interface DomainScores {
  FILE?: number;
  DEVICE?: number;
  LOGON?: number;
  HTTP?: number;
  file?: number;
  device?: number;
  logon?: number;
  http?: number;
}

/**
 * Machine Learning scenario classification predicted by XGBoost in `server/model_bridge.py`.
 */
export interface PredictedScenario {
  scenario: string;
  confidence: number;
}

/**
 * Integrity signal generated by endpoint tamper detectors (e.g. heartbeat anomalies, clock skew).
 */
export interface TamperSignal {
  is_anomaly?: boolean;
  score?: number;
  reason?: string;
  detector_name?: string;
}

/**
 * Multi-source correlated signals bundle attached to every risk event.
 * Combines heuristics, machine learning inference, and telemetry tamper signals.
 */
export interface CorrelatedSignals {
  cert_scenarios?: CertScenario[];
  heuristics?: {
    short_term_risk?: number;
    overall_score?: number;
    overall_severity?: string;
    detected_scenarios?: string[];
    detections?: HeuristicDetection[];
    domain_scores?: DomainScores;
  };
  predicted_scenario?: PredictedScenario;
  tamper_detector?: TamperSignal;
  domain_scores?: DomainScores;
  logon_risk?: number;
  file_risk?: number;
  device_risk?: number;
  http_risk?: number;
  [key: string]: unknown;
}

/**
 * Correlated threat record persisted in PostgreSQL `risk_events` table.
 */
export interface RiskEvent {
  id?: number | string;
  username: string;
  hostname?: string;
  risk_score: number | string;
  risk_level?: string;
  _computed_level?: string;
  summary?: string;
  correlated_signals_json?: string | CorrelatedSignals;
  created_at: string;
}

/**
 * Endpoint host registration record from PostgreSQL `agents` table.
 */
export interface AgentEndpoint {
  agent_id?: string;
  hostname: string;
  username_last_seen: string;
  status: 'active' | 'offline' | 'tampered' | string;
  last_seen_at: string;
  ip_address?: string;
  os_version?: string;
  client_version?: string;
}

/**
 * Ingestion counters grouped by active collector plugin.
 */
export interface CollectorCounts {
  [collectorName: string]: number;
}

/**
 * Storage metrics reported by the backend database.
 */
export interface StorageStats {
  agents?: number;
  risk_events?: number;
  anomalies?: number;
  collector_results?: number;
  collector_counts?: CollectorCounts;
  [key: string]: unknown;
}

/**
 * Host online/offline status counts derived from 5-minute heartbeat timestamps.
 */
export interface PCStatus {
  total_pcs: number;
  online_pcs: number;
  offline_pcs: number;
  /** Complete unique-hostname snapshot; independent of the paginated agent list. */
  endpoints?: FleetEndpoint[];
  /** Older servers used these counter names. */
  total_count?: number;
  online_count?: number;
  offline_count?: number;
}

export interface FleetEndpoint {
  hostname: string;
  status: 'online' | 'offline';
  last_seen_at: string | null;
}

/**
 * Aggregate counts of active endpoints categorized by risk severity level.
 */
export interface RiskCounts {
  critical: number;
  high: number;
  medium: number;
  low: number;
}

/**
 * Comprehensive dashboard telemetry envelope returned by `GET /api/dashboard-summary`.
 */
export interface DashboardSummary {
  ok: boolean;
  pc_status: PCStatus;
  risk_counts: RiskCounts;
  risk_events: RiskEvent[];
  anomalies?: unknown[];
  agents: AgentEndpoint[];
  users: string[];
  stats: StorageStats;
  total_risk_events: number;
  error?: string;
}

/**
 * Deep behavioral prediction response for a single target identity from `GET /api/user-predictions/{username}`.
 */
export interface UserPrediction {
  behavioral_risk: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  rvfl_error: number;
  score: number;
  confidence: number;
  predicted_scenario: {
    scenario: string;
    confidence: number;
  };
  recommended_action: string;
}

export interface UserPredictionResponse {
  ok: boolean;
  username: string;
  predictions: UserPrediction | null;
  message?: string;
  error?: string;
}

export interface UserRiskScoresResponse {
  ok: boolean;
  username: string;
  risk_scores: RiskEvent[];
  error?: string;
}

/**
 * Raw telemetry event record from PostgreSQL `collector_results` table.
 */
export interface TelemetryLog {
  id?: number | string;
  event_id?: string;
  collected_at: string;
  timestamp?: string;
  agent_id?: string;
  hostname: string;
  username: string;
  collector: string;
  collector_name?: string;
  status: 'success' | 'warning' | 'error' | string;
  summary_preview?: string;
  payload?: Record<string, unknown> | string;
  payload_json?: string;
  payload_id?: string;
  features?: Record<string, unknown>;
  risk?: Record<string, unknown>;
}

export interface TelemetryResponse {
  ok: boolean;
  logs: TelemetryLog[];
  events?: TelemetryLog[];
  total?: number | null;
  has_more?: boolean;
  next_cursor?: string | null;
  source?: 'postgres' | 'clickhouse';
  offset?: number;
  limit?: number;
  error?: string;
}

export interface TelemetryExplorerEvent {
  event_id: string;
  id?: string;
  timestamp: string;
  collected_at?: string;
  agent_id?: string;
  collector_name: string;
  collector?: string;
  hostname?: string;
  username?: string;
  status: string;
  summary_preview: string;
  payload?: Record<string, unknown> | string;
}

export interface TelemetryExplorerResponse {
  ok: boolean;
  events: TelemetryExplorerEvent[];
  logs?: TelemetryExplorerEvent[];
  next_cursor?: string | null;
  has_more?: boolean;
  source?: 'postgres' | 'clickhouse';
  limit?: number;
  error?: string;
}

export interface TelemetryHistogramBucket {
  timestamp: string;
  count: number;
}

export interface TelemetryHistogramResponse {
  ok: boolean;
  time_range: string;
  interval: string;
  total_events: number;
  histogram: TelemetryHistogramBucket[];
  error?: string;
}

export interface TelemetryEventDetailResponse {
  ok: boolean;
  event?: TelemetryLog;
  error?: string;
}

/**
 * Backend health check payload returned by `GET /api/health`.
 */
export interface SystemHealth {
  ok?: boolean;
  status?: string;
  model_pipeline?: 'ready' | 'missing_artifacts' | 'missing_dependencies' | 'disabled' | string;
  model_missing_artifacts?: string[];
  model_missing_dependencies?: string[];
  database?: 'ok' | 'error' | 'not_configured' | string;
  crypto?: string;
  queue_backend?: string;
  queue_status?: 'ok' | 'degraded' | 'unavailable' | string;
  sse_subscribers?: Record<string, number>;
  [key: string]: unknown;
}

export interface TamperAlertsResponse {
  ok: boolean;
  alerts: RiskEvent[];
  error?: string;
}

/**
 * Computed presentation model representing a single endpoint in the SOC Matrix table.
 * Includes threat decay status and normalized scenario badges.
 */
export interface EndpointRow {
  agentId: string;
  hostname: string;
  user: string;
  score: number;
  level: RiskLevel;
  isDecayed: boolean;
  scenarios: Array<{ id: string; desc: string }>;
  lastSeen: string;
  isOnline: boolean;
}

